config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :tweets
  resources :friends
  get ':controller/:action/:user_1/with_user/:user_2', :as => :user_compare

  root 'friends#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
	has_many :tweets
	validates :firstName, presence: true
	validates :twitterHandle, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :friend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	def create
		@friend = Friend.new(friend_params)
		@friend['twitterHandle'] = @friend['twitterHandle'].gsub(/@/,"")
		begin
			clientData = CLIENT.user(@friend.twitterHandle)
			if clientData.created?
				@friend['firstName'] = clientData.name
				@friend['friendImgURL'] = clientData.profile_image_url
				@friend['friendDescription'] = clientData.description
				@friend.save

					tweets = CLIENT.user_timeline(@friend.twitterHandle)
					(9).downto(0).each do |i|
						lastTweetTime = Tweet.where(twitterHandle:@friend.twitterHandle).maximum("tweetTime")
						newTweet = Tweet.new
						if tweets[i] == nil
							newTweet.twitterHandle = @friend.twitterHandle
							newTweet.tweetTime = 10000
							newTweet.tweetScore = 50
							newTweet.tweetText = ""
							newTweet.save
						else
							newTweet.twitterHandle = @friend.twitterHandle
							newTweet.tweetTime = tweets[i].created_at.to_i
							newTweet.tweetText = tweets[i].text.chomp
							newTweet.tweetScore = (Indico.sentiment(newTweet.tweetText)*100).round
							newTweet.save
						end
					end

				redirect_to :friend
			end
		rescue
			redirect_to :friends
		end

	end

	def new
	end

	def index
		@friends = Friend.all
		@friendArray = []
		Friend.all.each do |friend|
			@friendArray << friend.twitterHandle
		end

		@scoreColorArray = [	
							"#FF5782", 	#00
							"#FF5782",	#01
							"#FF5782",	#02
							"#FF5782",	#03
							"#607D8B",	#04
							"#607D8B", 	#05
							"#607D8B",	#06
							"#8BC34A",	#07
							"#8BC34A",	#08
							"#8BC34A",	#09
							"#8BC34A" ]	#10
		@dropdownColorArray = [
							"#F57C00", 	#00
							"#F57C00",	#01
							"#F57C00",	#02
							"#F57C00",	#03
							"#CFD8DC",	#04
							"#CFD8DC", 	#05
							"#CFD8DC",	#06
							"#DCEDC8",	#07
							"#DCEDC8",	#08
							"#DCEDC8",	#09
							"#DCEDC8" ]	#10
	end
	
	def show
		@latestTweets = Tweet.where(twitterHandle:params[:id]).order(Tweet.arel_table[:tweetTime].desc).limit(10)
		@friend = Friend.where(twitterHandle:params[:id])
		
	end

	def destroy
		Friend.where(twitterHandle:params[:id]).destroy_all
		Tweet.where(twitterHandle:params[:id]).destroy_all
		redirect_to '/'
	end
	
	def compare
		@user1 = params[:user_1]
		@user2 = params[:user_2]

		@user1LatestTweets = Tweet.where(twitterHandle:params[:user_1]).order(Tweet.arel_table[:tweetTime].desc).limit(10)
		@user2LatestTweets = Tweet.where(twitterHandle:params[:user_2]).order(Tweet.arel_table[:tweetTime].desc).limit(10)
		
		@user1Friend = Friend.where(twitterHandle:params[:user_1]).to_a
		@user2Friend = Friend.where(twitterHandle:params[:user_2]).to_a
		
	end

	private
		def friend_params
			params.require(:friend).permit(:twitterHandle)
		end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def index
	end
	def new
	end
	def create
	end
	def show
		
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Twitter::Autolink
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/compare.html.erb
<div class="row" >
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text hoverCard1" style="background-color:<%= @scoreColor %>" >
              <span class="card-title"> <img src="<%= Friend.where(twitterHandle:@user1Friend[0].twitterHandle)[0].friendImgURL%>"> <%= link_to @user1Friend[0].firstName, "/friends/" + @user1Friend[0].twitterHandle %> 
                <i><%=link_to "@" + @user1Friend[0].twitterHandle, "http://twitter.com/" + @user1Friend[0].twitterHandle %></i>
              </span>
              <h5 class='tweet'><div id='reporting1'>Hover over chart below to view prior tweets.</div></h5>
            </div>
          </div>
        </div>

<!-- Second Card -->

        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text hoverCard2" style="background-color:<%= @scoreColor %>" >
              <span class="card-title"> <img src="<%= Friend.where(twitterHandle:@user2Friend[0].twitterHandle)[0].friendImgURL %>"> <%= link_to @user2Friend[0].firstName, "/friends/" + @user2Friend[0].twitterHandle %> 
                <i><%=link_to "@" + @user2Friend[0].twitterHandle, "http://twitter.com/" + @user2Friend[0].twitterHandle %></i>
              </span>
              <h5 class='tweet'><div id='reporting2'>Hover over chart below to view prior tweets.</div></h5>
            </div>
          </div>
        </div>
      </div>



<!-- Start Chart   -->
<div id="container" style="width:100%; height:400px;"></div>


      <script>
$(function () {
    var $reporting1 = $('#reporting1');
    var $reporting2 = $('#reporting2');
    var $hoverScore1 = $('#hoverScore1');
    var $hoverScore2 = $('#hoverScore2');
    var colorArray = [      "#FF5782",  
                            "#FF5782",  
                            "#FF5782",  
                            "#FF5782",  
                            "#607D8B",  
                            "#607D8B",  
                            "#607D8B",  
                            "#8BC34A",  
                            "#8BC34A",  
                            "#8BC34A",  
                            "#8BC34A" ]
    var chart = new Highcharts.Chart({
        chart: {
            renderTo: 'container',
            type: 'spline',
            backgroundColor: 'rgba(255, 255, 255, 0.1)'
        },  

        title: {
            text: ""
        },
        credits: {
            enabled: false
        },
        xAxis: {

            categories: ['Earliest Tweet','','','','','','','','',"Latest Tweet"]
        },
        yAxis: {
            min: 0,
            max: 100,
            title: {
              text: "Sentiment Analysis Scores"
            }
        },
        
        series: [{
            name: '<%= @user1Friend[0].firstName %>',
            data: [{
                y: <%= @user1LatestTweets[9].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[9].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[9].tweetScore %>
            }, {
                y: <%= @user1LatestTweets[8].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[8].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[8].tweetScore %>
            }, {
                y: <%= @user1LatestTweets[7].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[7].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[7].tweetScore %>
            },{
                y: <%= @user1LatestTweets[6].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[6].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[6].tweetScore %>
            },{
                y: <%= @user1LatestTweets[5].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[5].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[5].tweetScore %>
            },{
                y: <%= @user1LatestTweets[4].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[4].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[4].tweetScore %>
            },{
                y: <%= @user1LatestTweets[3].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[3].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[3].tweetScore %>
            },{
                y: <%= @user1LatestTweets[2].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[2].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[2].tweetScore %>
            },{
                y: <%= @user1LatestTweets[1].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[1].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[1].tweetScore %>
            },{
                y: <%= @user1LatestTweets[0].tweetScore %>,
                tweet1: "<%= @user1LatestTweets[0].tweetText.gsub(/\n/,"") %>",
                tweet1val: <%= @user1LatestTweets[0].tweetScore %>
            }]
        },{
            name: '<%= @user2Friend[0].firstName %>',
            data: [{
                y: <%= @user2LatestTweets[9].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[9].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[9].tweetScore %>
            }, {
                y: <%= @user2LatestTweets[8].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[8].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[8].tweetScore %>
            }, {
                y: <%= @user2LatestTweets[7].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[7].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[7].tweetScore %>
            },{
                y: <%= @user2LatestTweets[6].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[6].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[6].tweetScore %>
            },{
                y: <%= @user2LatestTweets[5].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[5].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[5].tweetScore %>
            },{
                y: <%= @user2LatestTweets[4].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[4].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[4].tweetScore %>
            },{
                y: <%= @user2LatestTweets[3].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[3].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[3].tweetScore %>
            },{
                y: <%= @user2LatestTweets[2].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[2].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[2].tweetScore %>
            },{
                y: <%= @user2LatestTweets[1].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[1].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[1].tweetScore %>
            },{
                y: <%= @user2LatestTweets[0].tweetScore %>,
                tweet2: "<%= @user2LatestTweets[0].tweetText.gsub(/\n/,"") %>",
                tweet2val: <%= @user2LatestTweets[0].tweetScore %>
            }]
        }






        ],
        plotOptions: {
            series: {
                point: {
                    events: {
                        mouseOver: function () {
                            $reporting1.html(this.tweet1).twitter_autolink();
                            $reporting2.html(this.tweet2).twitter_autolink();
                            $('.hoverCard1').css('background-color', colorArray[Math.round((this.tweet1val)/10)]);
                            $('.hoverCard2').css('background-color', colorArray[Math.round((this.tweet2val)/10)]);
                        }
                    }
                }

            }
        },
        tooltip: {
            animation: false,
            followPointer: false,
            shadow: false,
        	shared: true,
            backgroundColor: 'rgba(255, 255, 255, 0.1)',
            borderColor: 'rgba(255, 255, 255, 0.1)',
            borderRadius: 10,
            borderWidth: 2,
            crosshairs: [true, false],
            formatter: function() {
            },
            positioner: function () {
                return { x: 10, y: 35 };
            }

        }
    });
});
</script>
<style>
.card,
.card-content {
	min-width: 100px;
	min-height: 450px;
}

</style>
<script>
$(document).ready( toast('Hover over the chart to view tweet mood history.', 8000));
</script>

app/views/friends/index.html.erb
<h4 style=""></h4>
<ul class="collapsible" data-collapsible="accordion">

<% @friends.each do |friend| %>
    <li>
    <% latestTweet = Tweet.where(twitterHandle:friend.twitterHandle).order(Tweet.arel_table[:tweetTime].desc).limit(1)[0] %>
    <% score = latestTweet.tweetScore %>

      <div class="collapsible-header" style="background-color:<%= @scoreColorArray[(score/10).round]%>; color=#FFFFFF ">

      	<span><img src="<%= Friend.where(twitterHandle:friend.twitterHandle)[0].friendImgURL %>" width="50" height="50"></span>
        <span style='color:#212121; font-size:2em;'><%= friend.firstName %></span>


      </div>
      <div class="collapsible-body" style="background-color:<%= @dropdownColorArray[(score/10).round]%>;">
      	<p style='font-size:1.8em'>
        <%= auto_link(latestTweet.tweetText).html_safe %>
      	</p>
        <p style='font-size:1.6em'>
       <%= link_to "More <i class='mdi-action-trending-up'></i>".html_safe, "friends/" + friend.twitterHandle, :style => 'font-weight:bold;' %>
        </p>
  	  </div>
    </li>
    <% end %>
</ul>
</div>

app/views/friends/new.html.erb
<h1> Add a new friend</h1>
<%= form_for :friend, url: friends_path do |f| %>
	<p>
		<i class="mdi-social-mood"></i>
		<%= f.label :twitterHandle, "Twitter Handle" %><br>
		<%= f.text_field :twitterHandle %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/friends/show.html.erb
<h5><span class="card-title"> <img style="width:70px" src="<%= Friend.where(twitterHandle:@friend[0].twitterHandle)[0].friendImgURL%>" > <%= @friend[0].firstName %> 
                <i><%=link_to "@" + @friend[0].twitterHandle, "http://twitter.com/" + @friend[0].twitterHandle %></i>
              </span>
<span class='right' >
                <a class="waves-effect waves-light btn" title="Delete" onclick="toast('<span>Remove Friend</span><a class=&quot;btn-flat yellow-text&quot; href=&quot;/friends/<%=@friend[0].twitterHandle%>&quot; data-method=&quot;delete&quot;>Confirm?<a>', 8000)"><i class='mdi-content-clear'></i></a>
                </span>
</h5>
<div class="row" >
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text hoverCard" style="background-color:<%= @scoreColor %>" >

              
              <div> <% if @friend[0].friendDescription %>
              <i><%= auto_link(@friend[0].friendDescription).html_safe %></i>
              <% end%> </div>
              <span class='right hoverScore'>
                </span>
              <h5 class='tweet' style='font-size:1.6em'><div id='reporting'>Hover over chart below to view prior tweets.</div></h5>
            </div>
          </div>
        </div>
      </div>
      
<div id="container" style="width:100%; height:300px;"></div>
      <script>
$(function () {
    var $reporting = $('#reporting');
    var $hoverScore = $('#hoverScore');
    var colorArray = [
                            "#FF5782",  
                            "#FF5782",  
                            "#FF5782",  
                            "#FF5782",  
                            "#607D8B",  
                            "#607D8B",  
                            "#607D8B",  
                            "#8BC34A",  
                            "#8BC34A",  
                            "#8BC34A",  
                            "#8BC34A" ] 
    var chart = new Highcharts.Chart({
        chart: {
            renderTo: 'container',
            type: 'areaspline',
            backgroundColor:'rgba(255, 255, 255, 0.1)'
        },  
        title: {
            text: ""
        },
        colors: ['#727272', '#727272'],
        credits: {
            enabled: false
        },
        xAxis: {

            categories: ['Earliest Tweet','','','','','','','','',"Latest Tweet"]
        },
        yAxis: {
            min: 0,
            max: 100,
            title: {
              text: "Sentiment Analysis Scores"
            }
        },
        
        series: [{
            showInLegend: false,
            data: [{
                y: <%= @latestTweets[9].tweetScore %>,
                tweet: "<%= @latestTweets[9].tweetText.gsub(/\n/,"") %>"
            }, {
                y: <%= @latestTweets[8].tweetScore %>,
                tweet: "<%= @latestTweets[8].tweetText.gsub(/\n/,"") %>"
            }, {
                y: <%= @latestTweets[7].tweetScore %>,
                tweet: "<%= @latestTweets[7].tweetText.gsub(/\n/,"") %>"
            },{
                y: <%= @latestTweets[6].tweetScore %>,
                tweet: "<%= @latestTweets[6].tweetText.gsub(/\n/,"") %>"
            },{
                y: <%= @latestTweets[5].tweetScore %>,
                tweet: "<%= @latestTweets[5].tweetText.gsub(/\n/,"") %>"
            },{
                y: <%= @latestTweets[4].tweetScore %>,
                tweet: "<%= @latestTweets[4].tweetText.gsub(/\n/,"") %>"
            },{
                y: <%= @latestTweets[3].tweetScore %>,
                tweet: "<%= @latestTweets[3].tweetText.gsub(/\n/,"") %>"
            },{
                y: <%= @latestTweets[2].tweetScore %>,
                tweet: "<%= @latestTweets[2].tweetText.gsub(/\n/,"") %>"
            },{
                y: <%= @latestTweets[1].tweetScore %>,
                tweet: "<%= @latestTweets[1].tweetText.gsub(/\n/,"") %>"
            },{
                y: <%= @latestTweets[0].tweetScore %>,
                tweet: "<%= @latestTweets[0].tweetText.gsub(/\n/,"") %>"
            }]
        }],
        plotOptions: {
            series: {
                point: {
                    events: {
                        mouseOver: function () {
                            $reporting.html(this.tweet).twitter_autolink();
                            $('.hoverCard').css('background-color', colorArray[Math.round((this.y)/10)]);
                        }
                    }
                }

            }
        },
        tooltip: {
            animation: false,
            followPointer: false,
            shadow: false,
            shared: true,
            backgroundColor: 'rgba(255, 255, 255, 0.1)',
            borderColor: 'rgba(255, 255, 255, 0.1)',
            borderRadius: 10,
            borderWidth: 2,
            crosshairs: [true, false],
            formatter: function() {
            },
            positioner: function () {
                return { x: 10, y: 35 };
            }

        }
    });
});
</script>

<script>
$(document).ready( toast('Hover over the chart to view tweet mood history.', 8000));
</script>

app/views/layouts/_footer.html.erb
<div style="width:730px; margin:0 auto;">
  <footer class="page-footer" style="background-color:#ff5722">
    <div class="container">

    </div>
    <div class="footer-copyright">
      <div class="container" style="float:left">
      © 2015 <a class="orange-text text-lighten-3" href="http://twitter.com/mikebashour">Mike Bashour</a>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<div style="width:730px; margin:0 auto; background-color:#FFFFFF; padding:0">
<nav class="lighten-1" role="navigation" style="background-color:#ff5722">
    <div class="container">
      <div class="nav-wrapper">

		<%= link_to "<i class = mdi-editor-mode-comment></i>Twentiments".html_safe, :friends, :class => "brand-logo" %>
      </div>

    <ul class="mobile">
      <li></li>
    </ul>
  </nav>
      <div class="row" style='height:47px'>
        <div class='col s3' style='font-size:30px'><a class="waves-effect waves-light modal-trigger" href="#modal1"><i class="mdi-social-person-add" style="font-size:30px"></i> Add</a></div>

        <div class='col s3'><%= link_to "<i class = mdi-action-dns></i> List".html_safe, :friends, :style => 'font-size:30px' %></div>

        <div class='col s3' style='font-size:30px'><a class="waves-effect waves-light modal-trigger" href="#modal2"><i class="mdi-action-swap-vert-circle" style="font-size:30px"></i> Compare</a></div>
        <div class='col s3'><%= link_to "<i class = mdi-action-stars></i> About".html_safe, "https://github.com/bashmb/twentiments", :style => 'font-size:30px; float:right' %></div>
    </div>





<!-- Modal Structure -->
<div id="modal1" class="modal full">
  <h4>Add new friend</h4>
    <p>Please enter your friend's Twitter handle below and click "Add Friend."</p>
    <%= form_for (Friend.new) do |f| %>
      <p>
        <%=  f.text_field :twitterHandle, :placeholder => "@Twitter Handle" %>
      </p>
      <div class="action-bar">
      <p >
      <button type="button" class="btn btn-default modal-close" data-dismiss="modal" style="float:left">Close</button>
      <button type="submit" class="btn btn-default modal-action" data-dismiss="modal"style="float:right">Add Friend</button>
        </p>
      </div>
    <% end %> 

</div>

<!-- Modal Structure -->
<div id="modal2" class="modal full">

  <h4>Compare Friends</h4>
    <p>To compare Twitter users, provide their Twitter handles below.</p>
    <%= form_tag("", method: "") do %>

      <p>

        <%=  text_field_tag('user_1', nil, :class => 'typeahead' )%>
        - with - 
        <%=  text_field_tag('user_2', nil, :class => 'typeahead' )%>
      </p>
<br>
<br>
      <div class="action-bar">
      <p>
      <button type="button" class="btn btn-default modal-close" data-dismiss="modal" style="float:left">Close</button>
      <button type="button" class="btn btn-default modal-action" id="compareBtn" data-dismiss="modal" style="float:right">Compare!</button>
        </p>
      </div>
    <% end %> 

</div>


<script>
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
</script>
<script>
  $('#compareBtn').click(function() {
      location.href = '/friends/compare/' + $('#user_1').val() + '/with_user/' + $('#user_2').val()
  });
</script>

<script>
var substringMatcher = function(strs) {
  return function findMatches(q, cb) {
    var matches, substrRegex;
 
    // an array that will be populated with substring matches
    matches = [];
 
    // regex used to determine if a string contains the substring `q`
    substrRegex = new RegExp(q, 'i');
 
    // iterate through the pool of strings and for any string that
    // contains the substring `q`, add it to the `matches` array
    $.each(strs, function(i, str) {
      if (substrRegex.test(str)) {
        // the typeahead jQuery plugin expects suggestions to a
        // JavaScript object, refer to typeahead docs for more info
        matches.push({ value: str });
      }
    });
 
    cb(matches);
  };
};

var friendsMatch = <%= raw @friendArray %>;
 
$('.typeahead').typeahead({
  hint: true,
  highlight: true,
  minLength: 2
},
{
  name: 'friendsMatch',
  displayKey: 'value',
  source: substringMatcher(friendsMatch)
});
</script>

<style>
.twitter-typeahead .tt-query,
.twitter-typeahead .tt-hint {
  margin-bottom: 0;
}
.tt-hint {
  display: block;
  width: 100%;
  height: 38px;
  padding: 8px 12px;
  font-size: 14px;
  line-height: 1.428571429;
  color: #999;
  vertical-align: middle;
  background-color: #ffffff;
  border: 1px solid #cccccc;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  -webkit-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
        transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
}
.tt-dropdown-menu {
  min-width: 160px;
  margin-top: 2px;
  padding: 5px 0;
  background-color: #ffffff;
  border: 1px solid #cccccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  background-clip: padding-box;
 
}
.tt-suggestion {
  display: block;
  padding: 3px 20px;
}
.tt-suggestion.tt-is-under-cursor {
  color: #fff;
  background-color: #428bca;
}
.tt-suggestion.tt-is-under-cursor a {
  color: #fff;
}
.tt-suggestion p {
  margin: 0;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twentiments</title>
  <!-- call favicon -->
  <%= favicon_link_tag 'favicon.ico' %>
  <!-- get stylesheets -->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <!-- get javascripts -->
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- include high charts. -->
  <script src="http://code.highcharts.com/highcharts.js"></script>
  <!-- include roboto font -->
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>

<script>
// Initialize collapse button
  $(".button-collapse").sideNav();
  </script>
</body>
</html>

app/views/welcome/index.html.erb
<h1> Welcome Page </h1>